import Head from 'next/head';
import styles from '../styles/Home.module.css';
import HomeBody from '@/components/HomeBody';

export default function Home() {
	return (
		<div>
			<Head>
				<title>{" Ruba's "} Blog</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<HomeBody />
		</div>
	);
}

/* export async function getServerSideProps() {
	const res = await fetch(`${API_URL}/api/posts`);
	const posts = await res.json();
	console.log(posts);
	return { props: { posts } };
} */
