import Head from 'next/head';
/* import dynamic from 'next/dynamic';

const DynamicComponentWithNoSSR = dynamic(
	() => import('./dashboard'),
	{ ssr: false }
); */
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { API_URL } from '@/config/index';
import HomeBody from '@/components/HomeBody'


export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Ruba's Blog</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
      <HomeBody />
			</main>
			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}

/* export async function getServerSideProps() {
	const res = await fetch(`${API_URL}/api/posts`);
	const posts = await res.json();
	console.log(posts);
	return { props: { posts } };
} */
